language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
      env: ENABLEDEBUG=true
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
    - os: osx
      osx_image: xcode11.3
      env: OSX=10.14 COMP=osxgcc
    - os: osx
      osx_image: xcode10
      env: OSX=10.13
      compiler: clang
before_script:
  - export ENABLEDEBUG=${ENABLEDEBUG:-false}
  - if [[ "$COMP" == "osxgcc" ]]; then brew update; brew install bash gcc; brew link --overwrite gcc; gcc --version; g++ --version; fi
script:
  - mkdir build
  - pushd build
  - export CFGFLAGS=""
  - if $ENABLEDEBUG ; then CFGFLAGS="$CFGFLAGS --enable-debug" ; fi
  - ../configure --prefix=$HOME/install $CFGFLAGS
  - make
  - make test
  - make install
