language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
      env: COINBREW_FLAGS=--enable-coinutils-bigindex
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
    - os: osx
      osx_image: xcode11
      env: OSX=10.14 CC=gcc CXX=g++ 
      compiler: clang
    - os: osx
      osx_image: xcode11
      env: OSX=10.14 
      compiler: clang
    - os: osx
      osx_image: xcode10
      env: OSX=10.13 
      compiler: clang

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [ x`brew list | fgrep bash` != x'bash' ]; then brew install bash; fi; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [ x`brew list | fgrep gcc` != x'gcc' ]; then brew install gcc; fi; fi
  - if [[ "$TRAVIS_OS_NAME $CC" == "osx gcc" ]]; then export CC=gcc-9 ; export CXX=g++-9 ; $CC --version; $CXX --version; gfortran --version; fi
  - cd ..
  - wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
  - export PROJECT_URL=https://github.com/$TRAVIS_REPO_SLUG
  - export PROJECT=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
  - bash ./coinbrew fetch $PROJECT_URL:$TRAVIS_BRANCH --no-prompt --skip-update  > /dev/null 

script:
  - bash ./coinbrew build $PROJECT --no-prompt --verbosity=2 --test $COINBREW_FLAGS
