platform:
  - x64

environment:
  global:
    MSYS2_BASEVER: 20150512
    MSYS2_ARCH: x86_64
  matrix:
    - HOST_ARCH_ARG: --host=x86_64-w64-mingw32
      ADD_PATH: /mingw64/bin
    - HOST_ARCH_ARG: --host=i686-w64-mingw32
      ADD_PATH: /mingw32/bin
    - HOST_ARCH_ARG: --enable-msvc
      ADD_PATH: /mingw64/bin

install:
  - C:\"Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - C:\msys64\usr\bin\bash -lc ""

build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; BuildTools/get.dependencies.sh fetch --no-third-party"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; export PATH=$PATH:$ADD_PATH; BuildTools/get.dependencies.sh build --monolithic --build=x86_64-w64-mingw32 $HOST_ARCH_ARG; cd build/CoinUtils/test; make; ls -l; nm unitTest.exe; dumpbin -SUMMARY unitTest.exe"
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw32\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%\build\CoinUtils\test
  - CALL .\unitTest.exe -mpsDir=..\..\Data\Sample"

test: off